services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - internal_network
    restart: always

  backend:
    build: ./server
    environment:
      DB_URL: ${DB_URL}
      PORT: ${PORT}
    networks:
      - internal_network
    ports:
      -"3002:3002"
    depends_on:
      - db
    restart: always

  frontend:
    build: ./client
    networks:
      - external_network
    ports:
      - "8088:80"
    restart: always

volumes:
  pgdata:

networks:
  internal_network:
  external_network:
